-- 1. 用户表
CREATE TABLE Users (
    UserID INT PRIMARY KEY AUTO_INCREMENT COMMENT '用户ID',
    UserName VARCHAR(20) NOT NULL UNIQUE COMMENT '用户名',
    Password VARCHAR(255) NOT NULL COMMENT '加密密码',  -- 增加密码字段长度以支持更强的哈希算法
    NickName VARCHAR(30) NOT NULL COMMENT '昵称',
    RemainingStorage BIGINT NOT NULL DEFAULT 5368709120 COMMENT '剩余存储(5GB)',
    Role TINYINT NOT NULL DEFAULT 1 COMMENT '1-普通用户 2-管理员',
    CreateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UpdateTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    CHECK (LENGTH(UserName) BETWEEN 4 AND 20),
    CHECK (Role IN (1,2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- 2. 资源表（复合分区）
CREATE TABLE Resource (
    ResID INT NOT NULL AUTO_INCREMENT COMMENT '资源ID',
    ResType TINYINT NOT NULL COMMENT '1-相册 2-照片 3-分享',
    UserID INT NOT NULL COMMENT '所属用户ID（关联Users表）',
    RelateID INT DEFAULT NULL COMMENT '关联资源ID',
    NameLink VARCHAR(255) NOT NULL COMMENT '相册名/照片名/分享链接',
    Ext1 VARCHAR(500) DEFAULT NULL COMMENT '相册描述/照片标签/分享有效期',
    Ext2 VARCHAR(255) DEFAULT NULL COMMENT '照片路径/照片格式',
    Ext3 BIGINT DEFAULT NULL COMMENT '照片大小/相册照片数',
    CreateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UpdateTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ResID, ResType),
    CHECK (ResType IN (1,2,3)),
    CHECK ((ResType=2 AND Ext3 <= 10485760 AND Ext3 > 0) OR ResType != 2),
    CHECK ((ResType=3 AND STR_TO_DATE(Ext1, '%Y-%m-%d %H:%i:%s') > CreateTime) OR ResType != 3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资源表'
PARTITION BY LIST (ResType) (
    PARTITION p_album VALUES IN (1),
    PARTITION p_photo VALUES IN (2),
    PARTITION p_share VALUES IN (3)
);

-- 3. 备份日志表
CREATE TABLE BackupLog (
    LogID INT PRIMARY KEY AUTO_INCREMENT,
    BackupDate DATETIME NOT NULL,
    Status VARCHAR(50) NOT NULL,
    Message TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='备份日志表';
