-- 1. 用户表
CREATE TABLE User (
    UserID INT PRIMARY KEY AUTO_INCREMENT COMMENT '用户ID',
    UserName VARCHAR(20) NOT NULL UNIQUE COMMENT '用户名',
    Password VARCHAR(50) NOT NULL COMMENT '加密密码',
    NickName VARCHAR(30) NOT NULL COMMENT '昵称',
    RemainingStorage BIGINT NOT NULL DEFAULT 5368709120 COMMENT '剩余存储(5GB)',
    Role TINYINT NOT NULL DEFAULT 1 COMMENT '1-普通用户 2-管理员',
    CHECK (LENGTH(UserName) BETWEEN 4 AND 20),
    CHECK (LENGTH(Password) BETWEEN 6 AND 20),
    CHECK (Role IN (1,2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';

-- 2. 资源表（复合分区）
CREATE TABLE Resource (
    ResID INT PRIMARY KEY AUTO_INCREMENT COMMENT '资源ID',
    ResType TINYINT NOT NULL COMMENT '1-相册 2-照片 3-分享',
    UserID INT NOT NULL COMMENT '所属用户ID',
    RelateID INT DEFAULT NULL COMMENT '关联资源ID',
    NameLink VARCHAR(255) NOT NULL COMMENT '相册名/照片名/分享链接',
    Ext1 VARCHAR(500) DEFAULT NULL COMMENT '相册描述/照片标签/分享有效期',
    Ext2 VARCHAR(255) DEFAULT NULL COMMENT '照片路径/照片格式',
    Ext3 BIGINT DEFAULT NULL COMMENT '照片大小/相册照片数',
    CreateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    CHECK (ResType IN (1,2,3)),
    CHECK ((ResType=2 AND Ext3 <= 10485760 AND Ext3 > 0) OR ResType != 2),
    CHECK ((ResType=3 AND STR_TO_DATE(Ext1, '%Y-%m-%d %H:%i:%s') > CreateTime) OR ResType != 3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='资源表'
PARTITION BY LIST (ResType)
SUBPARTITION BY RANGE (TO_DAYS(CreateTime)) (
    PARTITION p_album VALUES IN (1) (SUBPARTITION p_album_all VALUES LESS THAN MAXVALUE),
    PARTITION p_photo VALUES IN (2) (
        SUBPARTITION p_photo_recent VALUES LESS THAN (TO_DAYS(NOW()-INTERVAL 3 MONTH)),
        SUBPARTITION p_photo_old VALUES LESS THAN MAXVALUE
    ),
    PARTITION p_share VALUES IN (3) (SUBPARTITION p_share_all VALUES LESS THAN MAXVALUE)
);
